# Generated by Django 4.2.6 on 2023-11-23 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pratama', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produk',
            name='gambar',
            field=models.ImageField(null=True, upload_to='gambar/banner', verbose_name='Gambar (640 x 640 pixel)'),
        ),
    ]
